/* converted on Tue Apr 6, 2021, 16:35 (UTC+08) by antlr_4-to-w3c v0.51 which is Copyright (c) 2011-2021 by Gunther Rademacher <grd@gmx.net> */

WS        ::= WHITESPACE
           | POUND_COMMENT
           | DASHDASH_COMMENT
          /* ws: definition */

EQUAL_OPERATOR
         ::= '='
ASSIGN_OPERATOR
         ::= ':='
NULL_SAFE_EQUAL_OPERATOR
         ::= '<=>'
GREATER_OR_EQUAL_OPERATOR
         ::= '>='
GREATER_THAN_OPERATOR
         ::= '>'
LESS_OR_EQUAL_OPERATOR
         ::= '<='
LESS_THAN_OPERATOR
         ::= '<'
NOT_EQUAL_OPERATOR
         ::= '!='
NOT_EQUAL2_OPERATOR
         ::= '<>'
PLUS_OPERATOR
         ::= '+'
MINUS_OPERATOR
         ::= '-'
MULT_OPERATOR
         ::= '*'
DIV_OPERATOR
         ::= '/'
MOD_OPERATOR
         ::= '%'
LOGICAL_NOT_OPERATOR
         ::= '!'
BITWISE_NOT_OPERATOR
         ::= '~'
SHIFT_LEFT_OPERATOR
         ::= '<<'
SHIFT_RIGHT_OPERATOR
         ::= '>>'
LOGICAL_AND_OPERATOR
         ::= '&&'
BITWISE_AND_OPERATOR
         ::= '&'
BITWISE_XOR_OPERATOR
         ::= '^'
LOGICAL_OR_OPERATOR
         ::= '||'
CONCAT_PIPES_SYMBOL ::= LOGICAL_OR_OPERATOR
BITWISE_OR_OPERATOR
         ::= '|'
DOT_SYMBOL
         ::= '.'
COMMA_SYMBOL
         ::= ','
SEMICOLON_SYMBOL
         ::= ';'
COLON_SYMBOL
         ::= ':'
OPEN_PAR_SYMBOL
         ::= '('
CLOSE_PAR_SYMBOL
         ::= ')'
OPEN_CURLY_SYMBOL
         ::= '{'
CLOSE_CURLY_SYMBOL
         ::= '}'
UNDERLINE_SYMBOL
         ::= '_'
JSON_SEPARATOR_SYMBOL
         ::= '->'
JSON_UNQUOTED_SEPARATOR_SYMBOL
         ::= '->>'
AT_SIGN_SYMBOL
         ::= '@'
AT_TEXT_SUFFIX
         ::= '@' SIMPLE_IDENTIFIER
AT_AT_SIGN_SYMBOL
         ::= '@@'
NULL2_SYMBOL
         ::= '\N'
PARAM_MARKER
         ::= '?'
 CH_A        ::= [aA]
 CH_B        ::= [bB]
 CH_C        ::= [cC]
 CH_D        ::= [dD]
 CH_E        ::= [eE]
 CH_F        ::= [fF]
 CH_G        ::= [gG]
 CH_H        ::= [hH]
 CH_I        ::= [iI]
 CH_J        ::= [jJ]
 CH_K        ::= [kK]
 CH_L        ::= [lL]
 CH_M        ::= [mM]
 CH_N        ::= [nN]
 CH_O        ::= [oO]
 CH_P        ::= [pP]
 CH_Q        ::= [qQ]
 CH_R        ::= [rR]
 CH_S        ::= [sS]
 CH_T        ::= [tT]
 CH_U        ::= [uU]
 CH_V        ::= [vV]
 CH_W        ::= [wW]
 CH_X        ::= [xX]
 CH_Y        ::= [yY]
 CH_Z        ::= [zZ]
DIGIT    ::= [0-9]
DIGITS   ::= DIGIT+
HEXDIGIT ::= [0-9a-fA-F]
HEX_NUMBER
         ::= '0x' HEXDIGIT+
           | "x'" HEXDIGIT+ "'"
BIN_NUMBER
         ::= '0b' [0-1]+
           | "b'" [0-1]+ "'"
INT_NUMBER
         ::= DIGITS
LONG_NUMBER ::= INT_NUMBER
ULONGLONG_NUMBER ::= INT_NUMBER
DECIMAL_NUMBER
         ::= DIGITS? DOT_SYMBOL DIGITS
FLOAT_NUMBER
         ::= ( DIGITS? DOT_SYMBOL )? DIGITS [eE] ( MINUS_OPERATOR | PLUS_OPERATOR )? DIGITS
DOT_IDENTIFIER
         ::= DOT_SYMBOL LETTER_WHEN_UNQUOTED_NO_DIGIT LETTER_WHEN_UNQUOTED*
ACCESSIBLE_SYMBOL
         ::= CH_A CH_C CH_C CH_E CH_S CH_S CH_I CH_B CH_L CH_E 
ACCOUNT_SYMBOL
         ::= CH_A CH_C CH_C CH_O CH_U CH_N CH_T 
ACTION_SYMBOL
         ::= CH_A CH_C CH_T CH_I CH_O CH_N 
ADD_SYMBOL
         ::= CH_A CH_D CH_D 
ADDDATE_SYMBOL
         ::= CH_A CH_D CH_D CH_D CH_A CH_T CH_E 
AFTER_SYMBOL
         ::= CH_A CH_F CH_T CH_E CH_R 
AGAINST_SYMBOL
         ::= CH_A CH_G CH_A CH_I CH_N CH_S CH_T 
AGGREGATE_SYMBOL
         ::= CH_A CH_G CH_G CH_R CH_E CH_G CH_A CH_T CH_E 
ALGORITHM_SYMBOL
         ::= CH_A CH_L CH_G CH_O CH_R CH_I CH_T CH_H CH_M 
ALL_SYMBOL
         ::= CH_A CH_L CH_L 
ALTER_SYMBOL
         ::= CH_A CH_L CH_T CH_E CH_R 
ALWAYS_SYMBOL
         ::= CH_A CH_L CH_W CH_A CH_Y CH_S 
ANALYSE_SYMBOL
         ::= CH_A CH_N CH_A CH_L CH_Y CH_S CH_E 
ANALYZE_SYMBOL
         ::= CH_A CH_N CH_A CH_L CH_Y CH_Z CH_E 
AND_SYMBOL
         ::= CH_A CH_N CH_D 
ANY_SYMBOL
         ::= CH_A CH_N CH_Y 
AS_SYMBOL
         ::= CH_A CH_S 
ASC_SYMBOL
         ::= CH_A CH_S CH_C 
ASCII_SYMBOL
         ::= CH_A CH_S CH_C CH_I CH_I 
ASENSITIVE_SYMBOL
         ::= CH_A CH_S CH_E CH_N CH_S CH_I CH_T CH_I CH_V CH_E 
AT_SYMBOL
         ::= CH_A CH_T 
AUTHORS_SYMBOL
         ::= CH_A CH_U CH_T CH_H CH_O CH_R CH_S 
AUTOEXTEND_SIZE_SYMBOL
         ::= CH_A CH_U CH_T CH_O CH_E CH_X CH_T CH_E CH_N CH_D '_' CH_S CH_I CH_Z CH_E 
AUTO_INCREMENT_SYMBOL
         ::= CH_A CH_U CH_T CH_O '_' CH_I CH_N CH_C CH_R CH_E CH_M CH_E CH_N CH_T 
AVG_ROW_LENGTH_SYMBOL
         ::= CH_A CH_V CH_G '_' CH_R CH_O CH_W '_' CH_L CH_E CH_N CH_G CH_T CH_H 
AVG_SYMBOL
         ::= CH_A CH_V CH_G 
BACKUP_SYMBOL
         ::= CH_B CH_A CH_C CH_K CH_U CH_P 
BEFORE_SYMBOL
         ::= CH_B CH_E CH_F CH_O CH_R CH_E 
BEGIN_SYMBOL
         ::= CH_B CH_E CH_G CH_I CH_N 
BETWEEN_SYMBOL
         ::= CH_B CH_E CH_T CH_W CH_E CH_E CH_N 
BIGINT_SYMBOL
         ::= CH_B CH_I CH_G CH_I CH_N CH_T 
BINARY_SYMBOL
         ::= CH_B CH_I CH_N CH_A CH_R CH_Y 
BINLOG_SYMBOL
         ::= CH_B CH_I CH_N CH_L CH_O CH_G 
BIN_NUM_SYMBOL
         ::= CH_B CH_I CH_N '_' CH_N CH_U CH_M 
BIT_AND_SYMBOL
         ::= CH_B CH_I CH_T '_' CH_A CH_N CH_D 
BIT_OR_SYMBOL
         ::= CH_B CH_I CH_T '_' CH_O CH_R 
BIT_SYMBOL
         ::= CH_B CH_I CH_T 
BIT_XOR_SYMBOL
         ::= CH_B CH_I CH_T '_' CH_X CH_O CH_R 
BLOB_SYMBOL
         ::= CH_B CH_L CH_O CH_B 
BLOCK_SYMBOL
         ::= CH_B CH_L CH_O CH_C CH_K 
BOOLEAN_SYMBOL
         ::= CH_B CH_O CH_O CH_L CH_E CH_A CH_N 
BOOL_SYMBOL
         ::= CH_B CH_O CH_O CH_L 
BOTH_SYMBOL
         ::= CH_B CH_O CH_T CH_H 
BTREE_SYMBOL
         ::= CH_B CH_T CH_R CH_E CH_E 
BY_SYMBOL
         ::= CH_B CH_Y 
BYTE_SYMBOL
         ::= CH_B CH_Y CH_T CH_E 
CACHE_SYMBOL
         ::= CH_C CH_A CH_C CH_H CH_E 
CALL_SYMBOL
         ::= CH_C CH_A CH_L CH_L 
CASCADE_SYMBOL
         ::= CH_C CH_A CH_S CH_C CH_A CH_D CH_E 
CASCADED_SYMBOL
         ::= CH_C CH_A CH_S CH_C CH_A CH_D CH_E CH_D 
CASE_SYMBOL
         ::= CH_C CH_A CH_S CH_E 
CAST_SYMBOL
         ::= CH_C CH_A CH_S CH_T 
CATALOG_NAME_SYMBOL
         ::= CH_C CH_A CH_T CH_A CH_L CH_O CH_G '_' CH_N CH_A CH_M CH_E 
CHAIN_SYMBOL
         ::= CH_C CH_H CH_A CH_I CH_N 
CHANGE_SYMBOL
         ::= CH_C CH_H CH_A CH_N CH_G CH_E 
CHANGED_SYMBOL
         ::= CH_C CH_H CH_A CH_N CH_G CH_E CH_D 
CHANNEL_SYMBOL
         ::= CH_C CH_H CH_A CH_N CH_N CH_E CH_L 
CHARSET_SYMBOL
         ::= CH_C CH_H CH_A CH_R CH_S CH_E CH_T 
CHARACTER_SYMBOL
         ::= CH_C CH_H CH_A CH_R CH_A CH_C CH_T CH_E CH_R 
CHAR_SYMBOL
         ::= CH_C CH_H CH_A CH_R 
CHECKSUM_SYMBOL
         ::= CH_C CH_H CH_E CH_C CH_K CH_S CH_U CH_M 
CHECK_SYMBOL
         ::= CH_C CH_H CH_E CH_C CH_K 
CIPHER_SYMBOL
         ::= CH_C CH_I CH_P CH_H CH_E CH_R 
CLASS_ORIGIN_SYMBOL
         ::= CH_C CH_L CH_A CH_S CH_S '_' CH_O CH_R CH_I CH_G CH_I CH_N 
CLIENT_SYMBOL
         ::= CH_C CH_L CH_I CH_E CH_N CH_T 
CLOSE_SYMBOL
         ::= CH_C CH_L CH_O CH_S CH_E 
COALESCE_SYMBOL
         ::= CH_C CH_O CH_A CH_L CH_E CH_S CH_C CH_E 
CODE_SYMBOL
         ::= CH_C CH_O CH_D CH_E 
COLLATE_SYMBOL
         ::= CH_C CH_O CH_L CH_L CH_A CH_T CH_E 
COLLATION_SYMBOL
         ::= CH_C CH_O CH_L CH_L CH_A CH_T CH_I CH_O CH_N 
COLUMNS_SYMBOL
         ::= CH_C CH_O CH_L CH_U CH_M CH_N CH_S 
COLUMN_SYMBOL
         ::= CH_C CH_O CH_L CH_U CH_M CH_N 
COLUMN_NAME_SYMBOL
         ::= CH_C CH_O CH_L CH_U CH_M CH_N '_' CH_N CH_A CH_M CH_E 
COLUMN_FORMAT_SYMBOL
         ::= CH_C CH_O CH_L CH_U CH_M CH_N '_' CH_F CH_O CH_R CH_M CH_A CH_T 
COMMENT_SYMBOL
         ::= CH_C CH_O CH_M CH_M CH_E CH_N CH_T 
COMMITTED_SYMBOL
         ::= CH_C CH_O CH_M CH_M CH_I CH_T CH_T CH_E CH_D 
COMMIT_SYMBOL
         ::= CH_C CH_O CH_M CH_M CH_I CH_T 
COMPACT_SYMBOL
         ::= CH_C CH_O CH_M CH_P CH_A CH_C CH_T 
COMPLETION_SYMBOL
         ::= CH_C CH_O CH_M CH_P CH_L CH_E CH_T CH_I CH_O CH_N 
COMPRESSED_SYMBOL
         ::= CH_C CH_O CH_M CH_P CH_R CH_E CH_S CH_S CH_E CH_D 
COMPRESSION_SYMBOL
         ::= CH_C CH_O CH_M CH_P CH_R CH_E CH_S CH_S CH_I CH_O CH_N 
CONCURRENT_SYMBOL
         ::= CH_C CH_O CH_N CH_C CH_U CH_R CH_R CH_E CH_N CH_T 
CONDITION_SYMBOL
         ::= CH_C CH_O CH_N CH_D CH_I CH_T CH_I CH_O CH_N 
CONNECTION_SYMBOL
         ::= CH_C CH_O CH_N CH_N CH_E CH_C CH_T CH_I CH_O CH_N 
CONSISTENT_SYMBOL
         ::= CH_C CH_O CH_N CH_S CH_I CH_S CH_T CH_E CH_N CH_T 
CONSTRAINT_SYMBOL
         ::= CH_C CH_O CH_N CH_S CH_T CH_R CH_A CH_I CH_N CH_T 
CONSTRAINT_CATALOG_SYMBOL
         ::= CH_C CH_O CH_N CH_S CH_T CH_R CH_A CH_I CH_N CH_T '_' CH_C CH_A CH_T CH_A CH_L CH_O CH_G 
CONSTRAINT_NAME_SYMBOL
         ::= CH_C CH_O CH_N CH_S CH_T CH_R CH_A CH_I CH_N CH_T '_' CH_N CH_A CH_M CH_E 
CONSTRAINT_SCHEMA_SYMBOL
         ::= CH_C CH_O CH_N CH_S CH_T CH_R CH_A CH_I CH_N CH_T '_' CH_S CH_C CH_H CH_E CH_M CH_A 
CONTAINS_SYMBOL
         ::= CH_C CH_O CH_N CH_T CH_A CH_I CH_N CH_S 
CONTEXT_SYMBOL
         ::= CH_C CH_O CH_N CH_T CH_E CH_X CH_T 
CONTINUE_SYMBOL
         ::= CH_C CH_O CH_N CH_T CH_I CH_N CH_U CH_E 
CONTRIBUTORS_SYMBOL
         ::= CH_C CH_O CH_N CH_T CH_R CH_I CH_B CH_U CH_T CH_O CH_R CH_S 
CONVERT_SYMBOL
         ::= CH_C CH_O CH_N CH_V CH_E CH_R CH_T 
COUNT_SYMBOL
         ::= CH_C CH_O CH_U CH_N CH_T 
CPU_SYMBOL
         ::= CH_C CH_P CH_U 
CREATE_SYMBOL
         ::= CH_C CH_R CH_E CH_A CH_T CH_E 
CROSS_SYMBOL
         ::= CH_C CH_R CH_O CH_S CH_S 
CUBE_SYMBOL
         ::= CH_C CH_U CH_B CH_E 
CURDATE_SYMBOL
         ::= CH_C CH_U CH_R CH_D CH_A CH_T CH_E 
CURRENT_SYMBOL
         ::= CH_C CH_U CH_R CH_R CH_E CH_N CH_T 
CURRENT_DATE_SYMBOL
         ::= CH_C CH_U CH_R CH_R CH_E CH_N CH_T '_' CH_D CH_A CH_T CH_E 
CURRENT_TIME_SYMBOL
         ::= CH_C CH_U CH_R CH_R CH_E CH_N CH_T '_' CH_T CH_I CH_M CH_E 
CURRENT_TIMESTAMP_SYMBOL
         ::= CH_C CH_U CH_R CH_R CH_E CH_N CH_T '_' CH_T CH_I CH_M CH_E CH_S CH_T CH_A CH_M CH_P 
CURRENT_USER_SYMBOL
         ::= CH_C CH_U CH_R CH_R CH_E CH_N CH_T '_' CH_U CH_S CH_E CH_R 
CURSOR_SYMBOL
         ::= CH_C CH_U CH_R CH_S CH_O CH_R 
CURSOR_NAME_SYMBOL
         ::= CH_C CH_U CH_R CH_S CH_O CH_R '_' CH_N CH_A CH_M CH_E 
CURTIME_SYMBOL
         ::= CH_C CH_U CH_R CH_T CH_I CH_M CH_E 
DATABASE_SYMBOL
         ::= CH_D CH_A CH_T CH_A CH_B CH_A CH_S CH_E 
DATABASES_SYMBOL
         ::= CH_D CH_A CH_T CH_A CH_B CH_A CH_S CH_E CH_S 
DATAFILE_SYMBOL
         ::= CH_D CH_A CH_T CH_A CH_F CH_I CH_L CH_E 
DATA_SYMBOL
         ::= CH_D CH_A CH_T CH_A 
DATETIME_SYMBOL
         ::= CH_D CH_A CH_T CH_E CH_T CH_I CH_M CH_E 
DATE_ADD_SYMBOL
         ::= CH_D CH_A CH_T CH_E '_' CH_A CH_D CH_D 
DATE_SUB_SYMBOL
         ::= CH_D CH_A CH_T CH_E '_' CH_S CH_U CH_B 
DATE_SYMBOL
         ::= CH_D CH_A CH_T CH_E 
DAYOFMONTH_SYMBOL
         ::= CH_D CH_A CH_Y CH_O CH_F CH_M CH_O CH_N CH_T CH_H 
DAY_HOUR_SYMBOL
         ::= CH_D CH_A CH_Y '_' CH_H CH_O CH_U CH_R 
DAY_MICROSECOND_SYMBOL
         ::= CH_D CH_A CH_Y '_' CH_M CH_I CH_C CH_R CH_O CH_S CH_E CH_C CH_O CH_N CH_D 
DAY_MINUTE_SYMBOL
         ::= CH_D CH_A CH_Y '_' CH_M CH_I CH_N CH_U CH_T CH_E 
DAY_SECOND_SYMBOL
         ::= CH_D CH_A CH_Y '_' CH_S CH_E CH_C CH_O CH_N CH_D 
DAY_SYMBOL
         ::= CH_D CH_A CH_Y 
DEALLOCATE_SYMBOL
         ::= CH_D CH_E CH_A CH_L CH_L CH_O CH_C CH_A CH_T CH_E 
DEC_SYMBOL
         ::= CH_D CH_E CH_C 
DECIMAL_NUM_SYMBOL
         ::= CH_D CH_E CH_C CH_I CH_M CH_A CH_L '_' CH_N CH_U CH_M 
DECIMAL_SYMBOL
         ::= CH_D CH_E CH_C CH_I CH_M CH_A CH_L 
DECLARE_SYMBOL
         ::= CH_D CH_E CH_C CH_L CH_A CH_R CH_E 
DEFAULT_SYMBOL
         ::= CH_D CH_E CH_F CH_A CH_U CH_L CH_T 
DEFAULT_AUTH_SYMBOL
         ::= CH_D CH_E CH_F CH_A CH_U CH_L CH_T '_' CH_A CH_U CH_T CH_H 
DEFINER_SYMBOL
         ::= CH_D CH_E CH_F CH_I CH_N CH_E CH_R 
DELAYED_SYMBOL
         ::= CH_D CH_E CH_L CH_A CH_Y CH_E CH_D 
DELAY_KEY_WRITE_SYMBOL
         ::= CH_D CH_E CH_L CH_A CH_Y '_' CH_K CH_E CH_Y '_' CH_W CH_R CH_I CH_T CH_E 
DELETE_SYMBOL
         ::= CH_D CH_E CH_L CH_E CH_T CH_E 
DESC_SYMBOL
         ::= CH_D CH_E CH_S CH_C 
DESCRIBE_SYMBOL
         ::= CH_D CH_E CH_S CH_C CH_R CH_I CH_B CH_E 
DES_KEY_FILE_SYMBOL
         ::= CH_D CH_E CH_S '_' CH_K CH_E CH_Y '_' CH_F CH_I CH_L CH_E 
DETERMINISTIC_SYMBOL
         ::= CH_D CH_E CH_T CH_E CH_R CH_M CH_I CH_N CH_I CH_S CH_T CH_I CH_C 
DIAGNOSTICS_SYMBOL
         ::= CH_D CH_I CH_A CH_G CH_N CH_O CH_S CH_T CH_I CH_C CH_S 
DIRECTORY_SYMBOL
         ::= CH_D CH_I CH_R CH_E CH_C CH_T CH_O CH_R CH_Y 
DISABLE_SYMBOL
         ::= CH_D CH_I CH_S CH_A CH_B CH_L CH_E 
DISCARD_SYMBOL
         ::= CH_D CH_I CH_S CH_C CH_A CH_R CH_D 
DISK_SYMBOL
         ::= CH_D CH_I CH_S CH_K 
DISTINCT_SYMBOL
         ::= CH_D CH_I CH_S CH_T CH_I CH_N CH_C CH_T 
DISTINCTROW_SYMBOL
         ::= CH_D CH_I CH_S CH_T CH_I CH_N CH_C CH_T CH_R CH_O CH_W 
DIV_SYMBOL
         ::= CH_D CH_I CH_V 
DOUBLE_SYMBOL
         ::= CH_D CH_O CH_U CH_B CH_L CH_E 
DO_SYMBOL
         ::= CH_D CH_O 
DROP_SYMBOL
         ::= CH_D CH_R CH_O CH_P 
DUAL_SYMBOL
         ::= CH_D CH_U CH_A CH_L 
DUMPFILE_SYMBOL
         ::= CH_D CH_U CH_M CH_P CH_F CH_I CH_L CH_E 
DUPLICATE_SYMBOL
         ::= CH_D CH_U CH_P CH_L CH_I CH_C CH_A CH_T CH_E 
DYNAMIC_SYMBOL
         ::= CH_D CH_Y CH_N CH_A CH_M CH_I CH_C 
EACH_SYMBOL
         ::= CH_E CH_A CH_C CH_H 
ELSE_SYMBOL
         ::= CH_E CH_L CH_S CH_E 
ELSEIF_SYMBOL
         ::= CH_E CH_L CH_S CH_E CH_I CH_F 
ENABLE_SYMBOL
         ::= CH_E CH_N CH_A CH_B CH_L CH_E 
ENCLOSED_SYMBOL
         ::= CH_E CH_N CH_C CH_L CH_O CH_S CH_E CH_D 
ENCRYPTION_SYMBOL
         ::= CH_E CH_N CH_C CH_R CH_Y CH_P CH_T CH_I CH_O CH_N 
END_SYMBOL
         ::= CH_E CH_N CH_D 
ENDS_SYMBOL
         ::= CH_E CH_N CH_D CH_S 
END_OF_INPUT_SYMBOL
         ::= CH_E CH_N CH_D '_' CH_O CH_F '_' CH_I CH_N CH_P CH_U CH_T 
ENGINES_SYMBOL
         ::= CH_E CH_N CH_G CH_I CH_N CH_E CH_S 
ENGINE_SYMBOL
         ::= CH_E CH_N CH_G CH_I CH_N CH_E 
ENUM_SYMBOL
         ::= CH_E CH_N CH_U CH_M 
ERROR_SYMBOL
         ::= CH_E CH_R CH_R CH_O CH_R 
ERRORS_SYMBOL
         ::= CH_E CH_R CH_R CH_O CH_R CH_S 
ESCAPED_SYMBOL
         ::= CH_E CH_S CH_C CH_A CH_P CH_E CH_D 
ESCAPE_SYMBOL
         ::= CH_E CH_S CH_C CH_A CH_P CH_E 
EVENTS_SYMBOL
         ::= CH_E CH_V CH_E CH_N CH_T CH_S 
EVENT_SYMBOL
         ::= CH_E CH_V CH_E CH_N CH_T 
EVERY_SYMBOL
         ::= CH_E CH_V CH_E CH_R CH_Y 
EXCHANGE_SYMBOL
         ::= CH_E CH_X CH_C CH_H CH_A CH_N CH_G CH_E 
EXECUTE_SYMBOL
         ::= CH_E CH_X CH_E CH_C CH_U CH_T CH_E 
EXISTS_SYMBOL
         ::= CH_E CH_X CH_I CH_S CH_T CH_S 
EXIT_SYMBOL
         ::= CH_E CH_X CH_I CH_T 
EXPANSION_SYMBOL
         ::= CH_E CH_X CH_P CH_A CH_N CH_S CH_I CH_O CH_N 
EXPIRE_SYMBOL
         ::= CH_E CH_X CH_P CH_I CH_R CH_E 
EXPLAIN_SYMBOL
         ::= CH_E CH_X CH_P CH_L CH_A CH_I CH_N 
EXPORT_SYMBOL
         ::= CH_E CH_X CH_P CH_O CH_R CH_T 
EXTENDED_SYMBOL
         ::= CH_E CH_X CH_T CH_E CH_N CH_D CH_E CH_D 
EXTENT_SIZE_SYMBOL
         ::= CH_E CH_X CH_T CH_E CH_N CH_T '_' CH_S CH_I CH_Z CH_E 
EXTRACT_SYMBOL
         ::= CH_E CH_X CH_T CH_R CH_A CH_C CH_T 
FALSE_SYMBOL
         ::= CH_F CH_A CH_L CH_S CH_E 
FAST_SYMBOL
         ::= CH_F CH_A CH_S CH_T 
FAULTS_SYMBOL
         ::= CH_F CH_A CH_U CH_L CH_T CH_S 
FETCH_SYMBOL
         ::= CH_F CH_E CH_T CH_C CH_H 
FIELDS_SYMBOL
         ::= CH_F CH_I CH_E CH_L CH_D CH_S 
FILE_SYMBOL
         ::= CH_F CH_I CH_L CH_E 
FILE_BLOCK_SIZE_SYMBOL
         ::= CH_F CH_I CH_L CH_E '_' CH_B CH_L CH_O CH_C CH_K '_' CH_S CH_I CH_Z CH_E 
FILTER_SYMBOL
         ::= CH_F CH_I CH_L CH_T CH_E CH_R 
FIRST_SYMBOL
         ::= CH_F CH_I CH_R CH_S CH_T 
FIXED_SYMBOL
         ::= CH_F CH_I CH_X CH_E CH_D 
FLOAT4_SYMBOL
         ::= CH_F CH_L CH_O CH_A CH_T '4'
FLOAT8_SYMBOL
         ::= CH_F CH_L CH_O CH_A CH_T '8'
FLOAT_SYMBOL
         ::= CH_F CH_L CH_O CH_A CH_T 
FLUSH_SYMBOL
         ::= CH_F CH_L CH_U CH_S CH_H 
FOLLOWS_SYMBOL
         ::= CH_F CH_O CH_L CH_L CH_O CH_W CH_S 
FORCE_SYMBOL
         ::= CH_F CH_O CH_R CH_C CH_E 
FOREIGN_SYMBOL
         ::= CH_F CH_O CH_R CH_E CH_I CH_G CH_N 
FOR_SYMBOL
         ::= CH_F CH_O CH_R 
FORMAT_SYMBOL
         ::= CH_F CH_O CH_R CH_M CH_A CH_T 
FOUND_SYMBOL
         ::= CH_F CH_O CH_U CH_N CH_D 
FROM_SYMBOL
         ::= CH_F CH_R CH_O CH_M 
FULL_SYMBOL
         ::= CH_F CH_U CH_L CH_L 
FULLTEXT_SYMBOL
         ::= CH_F CH_U CH_L CH_L CH_T CH_E CH_X CH_T 
FUNCTION_SYMBOL
         ::= CH_F CH_U CH_N CH_C CH_T CH_I CH_O CH_N 
GET_SYMBOL
         ::= CH_G CH_E CH_T 
GENERAL_SYMBOL
         ::= CH_G CH_E CH_N CH_E CH_R CH_A CH_L 
GENERATED_SYMBOL
         ::= CH_G CH_E CH_N CH_E CH_R CH_A CH_T CH_E CH_D 
GROUP_REPLICATION_SYMBOL
         ::= CH_G CH_R CH_O CH_U CH_P '_' CH_R CH_E CH_P CH_L CH_I CH_C CH_A CH_T CH_I CH_O CH_N 
GEOMETRYCOLLECTION_SYMBOL
         ::= CH_G CH_E CH_O CH_M CH_E CH_T CH_R CH_Y CH_C CH_O CH_L CH_L CH_E CH_C CH_T CH_I CH_O CH_N 
GEOMETRY_SYMBOL
         ::= CH_G CH_E CH_O CH_M CH_E CH_T CH_R CH_Y 
GET_FORMAT_SYMBOL
         ::= CH_G CH_E CH_T '_' CH_F CH_O CH_R CH_M CH_A CH_T 
GLOBAL_SYMBOL
         ::= CH_G CH_L CH_O CH_B CH_A CH_L 
GRANT_SYMBOL
         ::= CH_G CH_R CH_A CH_N CH_T 
GRANTS_SYMBOL
         ::= CH_G CH_R CH_A CH_N CH_T CH_S 
GROUP_SYMBOL
         ::= CH_G CH_R CH_O CH_U CH_P 
GROUP_CONCAT_SYMBOL
         ::= CH_G CH_R CH_O CH_U CH_P '_' CH_C CH_O CH_N CH_C CH_A CH_T 
HANDLER_SYMBOL
         ::= CH_H CH_A CH_N CH_D CH_L CH_E CH_R 
HASH_SYMBOL
         ::= CH_H CH_A CH_S CH_H 
HAVING_SYMBOL
         ::= CH_H CH_A CH_V CH_I CH_N CH_G 
HELP_SYMBOL
         ::= CH_H CH_E CH_L CH_P 
HIGH_PRIORITY_SYMBOL
         ::= CH_H CH_I CH_G CH_H '_' CH_P CH_R CH_I CH_O CH_R CH_I CH_T CH_Y 
HOST_SYMBOL
         ::= CH_H CH_O CH_S CH_T 
HOSTS_SYMBOL
         ::= CH_H CH_O CH_S CH_T CH_S 
HOUR_MICROSECOND_SYMBOL
         ::= CH_H CH_O CH_U CH_R '_' CH_M CH_I CH_C CH_R CH_O CH_S CH_E CH_C CH_O CH_N CH_D 
HOUR_MINUTE_SYMBOL
         ::= CH_H CH_O CH_U CH_R '_' CH_M CH_I CH_N CH_U CH_T CH_E 
HOUR_SECOND_SYMBOL
         ::= CH_H CH_O CH_U CH_R '_' CH_S CH_E CH_C CH_O CH_N CH_D 
HOUR_SYMBOL
         ::= CH_H CH_O CH_U CH_R 
IDENTIFIED_SYMBOL
         ::= CH_I CH_D CH_E CH_N CH_T CH_I CH_F CH_I CH_E CH_D 
IF_SYMBOL
         ::= CH_I CH_F 
IGNORE_SYMBOL
         ::= CH_I CH_G CH_N CH_O CH_R CH_E 
IGNORE_SERVER_IDS_SYMBOL
         ::= CH_I CH_G CH_N CH_O CH_R CH_E '_' CH_S CH_E CH_R CH_V CH_E CH_R '_' CH_I CH_D CH_S 
IMPORT_SYMBOL
         ::= CH_I CH_M CH_P CH_O CH_R CH_T 
INDEXES_SYMBOL
         ::= CH_I CH_N CH_D CH_E CH_X CH_E CH_S 
INDEX_SYMBOL
         ::= CH_I CH_N CH_D CH_E CH_X 
INFILE_SYMBOL
         ::= CH_I CH_N CH_F CH_I CH_L CH_E 
INITIAL_SIZE_SYMBOL
         ::= CH_I CH_N CH_I CH_T CH_I CH_A CH_L '_' CH_S CH_I CH_Z CH_E 
INNER_SYMBOL
         ::= CH_I CH_N CH_N CH_E CH_R 
INOUT_SYMBOL
         ::= CH_I CH_N CH_O CH_U CH_T 
INSENSITIVE_SYMBOL
         ::= CH_I CH_N CH_S CH_E CH_N CH_S CH_I CH_T CH_I CH_V CH_E 
INSERT_SYMBOL
         ::= CH_I CH_N CH_S CH_E CH_R CH_T 
INSERT_METHOD_SYMBOL
         ::= CH_I CH_N CH_S CH_E CH_R CH_T '_' CH_M CH_E CH_T CH_H CH_O CH_D 
INSTANCE_SYMBOL
         ::= CH_I CH_N CH_S CH_T CH_A CH_N CH_C CH_E 
INSTALL_SYMBOL
         ::= CH_I CH_N CH_S CH_T CH_A CH_L CH_L 
INTEGER_SYMBOL
         ::= CH_I CH_N CH_T CH_E CH_G CH_E CH_R 
INTERVAL_SYMBOL
         ::= CH_I CH_N CH_T CH_E CH_R CH_V CH_A CH_L 
INTO_SYMBOL
         ::= CH_I CH_N CH_T CH_O 
INT_SYMBOL
         ::= CH_I CH_N CH_T 
INVOKER_SYMBOL
         ::= CH_I CH_N CH_V CH_O CH_K CH_E CH_R 
IN_SYMBOL
         ::= CH_I CH_N 
IO_AFTER_GTIDS_SYMBOL
         ::= CH_I CH_O '_' CH_A CH_F CH_T CH_E CH_R '_' CH_G CH_T CH_I CH_D CH_S 
IO_BEFORE_GTIDS_SYMBOL
         ::= CH_I CH_O '_' CH_B CH_E CH_F CH_O CH_R CH_E '_' CH_G CH_T CH_I CH_D CH_S 
IO_THREAD_SYMBOL
         ::= CH_I CH_O '_' CH_T CH_H CH_R CH_E CH_A CH_D 
IO_SYMBOL
         ::= CH_I CH_O 
IPC_SYMBOL
         ::= CH_I CH_P CH_C 
IS_SYMBOL
         ::= CH_I CH_S 
ISOLATION_SYMBOL
         ::= CH_I CH_S CH_O CH_L CH_A CH_T CH_I CH_O CH_N 
ISSUER_SYMBOL
         ::= CH_I CH_S CH_S CH_U CH_E CH_R 
ITERATE_SYMBOL
         ::= CH_I CH_T CH_E CH_R CH_A CH_T CH_E 
JOIN_SYMBOL
         ::= CH_J CH_O CH_I CH_N 
JSON_SYMBOL
         ::= CH_J CH_S CH_O CH_N 
KEYS_SYMBOL
         ::= CH_K CH_E CH_Y CH_S 
KEY_BLOCK_SIZE_SYMBOL
         ::= CH_K CH_E CH_Y '_' CH_B CH_L CH_O CH_C CH_K '_' CH_S CH_I CH_Z CH_E 
KEY_SYMBOL
         ::= CH_K CH_E CH_Y 
KILL_SYMBOL
         ::= CH_K CH_I CH_L CH_L 
LANGUAGE_SYMBOL
         ::= CH_L CH_A CH_N CH_G CH_U CH_A CH_G CH_E 
LAST_SYMBOL
         ::= CH_L CH_A CH_S CH_T 
LEADING_SYMBOL
         ::= CH_L CH_E CH_A CH_D CH_I CH_N CH_G 
LEAVES_SYMBOL
         ::= CH_L CH_E CH_A CH_V CH_E CH_S 
LEAVE_SYMBOL
         ::= CH_L CH_E CH_A CH_V CH_E 
LEFT_SYMBOL
         ::= CH_L CH_E CH_F CH_T 
LESS_SYMBOL
         ::= CH_L CH_E CH_S CH_S 
LEVEL_SYMBOL
         ::= CH_L CH_E CH_V CH_E CH_L 
LIKE_SYMBOL
         ::= CH_L CH_I CH_K CH_E 
LIMIT_SYMBOL
         ::= CH_L CH_I CH_M CH_I CH_T 
LINEAR_SYMBOL
         ::= CH_L CH_I CH_N CH_E CH_A CH_R 
LINES_SYMBOL
         ::= CH_L CH_I CH_N CH_E CH_S 
LINESTRING_SYMBOL
         ::= CH_L CH_I CH_N CH_E CH_S CH_T CH_R CH_I CH_N CH_G 
LIST_SYMBOL
         ::= CH_L CH_I CH_S CH_T 
LOAD_SYMBOL
         ::= CH_L CH_O CH_A CH_D 
LOCALTIME_SYMBOL
         ::= CH_L CH_O CH_C CH_A CH_L CH_T CH_I CH_M CH_E 
LOCALTIMESTAMP_SYMBOL
         ::= CH_L CH_O CH_C CH_A CH_L CH_T CH_I CH_M CH_E CH_S CH_T CH_A CH_M CH_P 
LOCAL_SYMBOL
         ::= CH_L CH_O CH_C CH_A CH_L 
LOCATOR_SYMBOL
         ::= CH_L CH_O CH_C CH_A CH_T CH_O CH_R 
LOCKS_SYMBOL
         ::= CH_L CH_O CH_C CH_K CH_S 
LOCK_SYMBOL
         ::= CH_L CH_O CH_C CH_K 
LOGFILE_SYMBOL
         ::= CH_L CH_O CH_G CH_F CH_I CH_L CH_E 
LOGS_SYMBOL
         ::= CH_L CH_O CH_G CH_S 
LONGBLOB_SYMBOL
         ::= CH_L CH_O CH_N CH_G CH_B CH_L CH_O CH_B 
LONGTEXT_SYMBOL
         ::= CH_L CH_O CH_N CH_G CH_T CH_E CH_X CH_T 
LONG_NUM_SYMBOL
         ::= CH_L CH_O CH_N CH_G '_' CH_N CH_U CH_M 
LONG_SYMBOL
         ::= CH_L CH_O CH_N CH_G 
LOOP_SYMBOL
         ::= CH_L CH_O CH_O CH_P 
LOW_PRIORITY_SYMBOL
         ::= CH_L CH_O CH_W '_' CH_P CH_R CH_I CH_O CH_R CH_I CH_T CH_Y 
MASTER_AUTO_POSITION_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_A CH_U CH_T CH_O '_' CH_P CH_O CH_S CH_I CH_T CH_I CH_O CH_N 
MASTER_BIND_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_B CH_I CH_N CH_D 
MASTER_CONNECT_RETRY_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_C CH_O CH_N CH_N CH_E CH_C CH_T '_' CH_R CH_E CH_T CH_R CH_Y 
MASTER_DELAY_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_D CH_E CH_L CH_A CH_Y 
MASTER_HOST_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_H CH_O CH_S CH_T 
MASTER_LOG_FILE_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_L CH_O CH_G '_' CH_F CH_I CH_L CH_E 
MASTER_LOG_POS_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_L CH_O CH_G '_' CH_P CH_O CH_S 
MASTER_PASSWORD_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_P CH_A CH_S CH_S CH_W CH_O CH_R CH_D 
MASTER_PORT_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_P CH_O CH_R CH_T 
MASTER_RETRY_COUNT_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_R CH_E CH_T CH_R CH_Y '_' CH_C CH_O CH_U CH_N CH_T 
MASTER_SERVER_ID_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_E CH_R CH_V CH_E CH_R '_' CH_I CH_D 
MASTER_SSL_CAPATH_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_S CH_L '_' CH_C CH_A CH_P CH_A CH_T CH_H 
MASTER_SSL_CA_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_S CH_L '_' CH_C CH_A 
MASTER_SSL_CERT_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_S CH_L '_' CH_C CH_E CH_R CH_T 
MASTER_SSL_CIPHER_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_S CH_L '_' CH_C CH_I CH_P CH_H CH_E CH_R 
MASTER_SSL_CRL_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_S CH_L '_' CH_C CH_R CH_L 
MASTER_SSL_CRLPATH_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_S CH_L '_' CH_C CH_R CH_L CH_P CH_A CH_T CH_H 
MASTER_SSL_KEY_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_S CH_L '_' CH_K CH_E CH_Y 
MASTER_SSL_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_S CH_L 
MASTER_SSL_VERIFY_SERVER_CERT_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_S CH_S CH_L '_' CH_V CH_E CH_R CH_I CH_F CH_Y '_' CH_S CH_E CH_R CH_V CH_E CH_R '_' CH_C CH_E CH_R CH_T 
MASTER_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R 
MASTER_TLS_VERSION_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_T CH_L CH_S '_' CH_V CH_E CH_R CH_S CH_I CH_O CH_N 
MASTER_USER_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_U CH_S CH_E CH_R 
MASTER_HEARTBEAT_PERIOD_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_H CH_E CH_A CH_R CH_T CH_B CH_E CH_A CH_T '_' CH_P CH_E CH_R CH_I CH_O CH_D 
MATCH_SYMBOL
         ::= CH_M CH_A CH_T CH_C CH_H 
MAX_CONNECTIONS_PER_HOUR_SYMBOL
         ::= CH_M CH_A CH_X '_' CH_C CH_O CH_N CH_N CH_E CH_C CH_T CH_I CH_O CH_N CH_S '_' CH_P CH_E CH_R '_' CH_H CH_O CH_U CH_R 
MAX_QUERIES_PER_HOUR_SYMBOL
         ::= CH_M CH_A CH_X '_' CH_Q CH_U CH_E CH_R CH_I CH_E CH_S '_' CH_P CH_E CH_R '_' CH_H CH_O CH_U CH_R 
MAX_ROWS_SYMBOL
         ::= CH_M CH_A CH_X '_' CH_R CH_O CH_W CH_S 
MAX_SIZE_SYMBOL
         ::= CH_M CH_A CH_X '_' CH_S CH_I CH_Z CH_E 
MAX_STATEMENT_TIME_SYMBOL
         ::= CH_M CH_A CH_X '_' CH_S CH_T CH_A CH_T CH_E CH_M CH_E CH_N CH_T '_' CH_T CH_I CH_M CH_E 
MAX_SYMBOL
         ::= CH_M CH_A CH_X 
MAX_UPDATES_PER_HOUR_SYMBOL
         ::= CH_M CH_A CH_X '_' CH_U CH_P CH_D CH_A CH_T CH_E CH_S '_' CH_P CH_E CH_R '_' CH_H CH_O CH_U CH_R 
MAX_USER_CONNECTIONS_SYMBOL
         ::= CH_M CH_A CH_X '_' CH_U CH_S CH_E CH_R '_' CH_C CH_O CH_N CH_N CH_E CH_C CH_T CH_I CH_O CH_N CH_S 
MAXVALUE_SYMBOL
         ::= CH_M CH_A CH_X CH_V CH_A CH_L CH_U CH_E 
MEDIUMBLOB_SYMBOL
         ::= CH_M CH_E CH_D CH_I CH_U CH_M CH_B CH_L CH_O CH_B 
MEDIUMINT_SYMBOL
         ::= CH_M CH_E CH_D CH_I CH_U CH_M CH_I CH_N CH_T 
MEDIUMTEXT_SYMBOL
         ::= CH_M CH_E CH_D CH_I CH_U CH_M CH_T CH_E CH_X CH_T 
MEDIUM_SYMBOL
         ::= CH_M CH_E CH_D CH_I CH_U CH_M 
MEMORY_SYMBOL
         ::= CH_M CH_E CH_M CH_O CH_R CH_Y 
MERGE_SYMBOL
         ::= CH_M CH_E CH_R CH_G CH_E 
MESSAGE_TEXT_SYMBOL
         ::= CH_M CH_E CH_S CH_S CH_A CH_G CH_E '_' CH_T CH_E CH_X CH_T 
MICROSECOND_SYMBOL
         ::= CH_M CH_I CH_C CH_R CH_O CH_S CH_E CH_C CH_O CH_N CH_D 
MID_SYMBOL
         ::= CH_M CH_I CH_D 
MIDDLEINT_SYMBOL
         ::= CH_M CH_I CH_D CH_D CH_L CH_E CH_I CH_N CH_T 
MIGRATE_SYMBOL
         ::= CH_M CH_I CH_G CH_R CH_A CH_T CH_E 
MINUTE_MICROSECOND_SYMBOL
         ::= CH_M CH_I CH_N CH_U CH_T CH_E '_' CH_M CH_I CH_C CH_R CH_O CH_S CH_E CH_C CH_O CH_N CH_D 
MINUTE_SECOND_SYMBOL
         ::= CH_M CH_I CH_N CH_U CH_T CH_E '_' CH_S CH_E CH_C CH_O CH_N CH_D 
MINUTE_SYMBOL
         ::= CH_M CH_I CH_N CH_U CH_T CH_E 
MIN_ROWS_SYMBOL
         ::= CH_M CH_I CH_N '_' CH_R CH_O CH_W CH_S 
MIN_SYMBOL
         ::= CH_M CH_I CH_N 
MODE_SYMBOL
         ::= CH_M CH_O CH_D CH_E 
MODIFIES_SYMBOL
         ::= CH_M CH_O CH_D CH_I CH_F CH_I CH_E CH_S 
MODIFY_SYMBOL
         ::= CH_M CH_O CH_D CH_I CH_F CH_Y 
MOD_SYMBOL
         ::= CH_M CH_O CH_D 
MONTH_SYMBOL
         ::= CH_M CH_O CH_N CH_T CH_H 
MULTILINESTRING_SYMBOL
         ::= CH_M CH_U CH_L CH_T CH_I CH_L CH_I CH_N CH_E CH_S CH_T CH_R CH_I CH_N CH_G 
MULTIPOINT_SYMBOL
         ::= CH_M CH_U CH_L CH_T CH_I CH_P CH_O CH_I CH_N CH_T 
MULTIPOLYGON_SYMBOL
         ::= CH_M CH_U CH_L CH_T CH_I CH_P CH_O CH_L CH_Y CH_G CH_O CH_N 
MUTEX_SYMBOL
         ::= CH_M CH_U CH_T CH_E CH_X 
MYSQL_ERRNO_SYMBOL
         ::= CH_M CH_Y CH_S CH_Q CH_L '_' CH_E CH_R CH_R CH_N CH_O 
NAMES_SYMBOL
         ::= CH_N CH_A CH_M CH_E CH_S 
NAME_SYMBOL
         ::= CH_N CH_A CH_M CH_E 
NATIONAL_SYMBOL
         ::= CH_N CH_A CH_T CH_I CH_O CH_N CH_A CH_L 
NATURAL_SYMBOL
         ::= CH_N CH_A CH_T CH_U CH_R CH_A CH_L 
NCHAR_STRING_SYMBOL
         ::= CH_N CH_C CH_H CH_A CH_R '_' CH_S CH_T CH_R CH_I CH_N CH_G 
NCHAR_SYMBOL
         ::= CH_N CH_C CH_H CH_A CH_R 
NDB_SYMBOL
         ::= CH_N CH_D CH_B 
NDBCLUSTER_SYMBOL
         ::= CH_N CH_D CH_B CH_C CH_L CH_U CH_S CH_T CH_E CH_R 
NEG_SYMBOL
         ::= CH_N CH_E CH_G 
NEVER_SYMBOL
         ::= CH_N CH_E CH_V CH_E CH_R 
NEW_SYMBOL
         ::= CH_N CH_E CH_W 
NEXT_SYMBOL
         ::= CH_N CH_E CH_X CH_T 
NODEGROUP_SYMBOL
         ::= CH_N CH_O CH_D CH_E CH_G CH_R CH_O CH_U CH_P 
NONE_SYMBOL
         ::= CH_N CH_O CH_N CH_E 
NONBLOCKING_SYMBOL
         ::= CH_N CH_O CH_N CH_B CH_L CH_O CH_C CH_K CH_I CH_N CH_G 
NOT_SYMBOL
         ::= CH_N CH_O CH_T 
NOT2_SYMBOL ::= NOT_SYMBOL
NOW_SYMBOL
         ::= CH_N CH_O CH_W 
NO_SYMBOL
         ::= CH_N CH_O 
NO_WAIT_SYMBOL
         ::= CH_N CH_O '_' CH_W CH_A CH_I CH_T 
NO_WRITE_TO_BINLOG_SYMBOL
         ::= CH_N CH_O '_' CH_W CH_R CH_I CH_T CH_E '_' CH_T CH_O '_' CH_B CH_I CH_N CH_L CH_O CH_G 
NULL_SYMBOL
         ::= CH_N CH_U CH_L CH_L 
NUMBER_SYMBOL
         ::= CH_N CH_U CH_M CH_B CH_E CH_R 
NUMERIC_SYMBOL
         ::= CH_N CH_U CH_M CH_E CH_R CH_I CH_C 
NVARCHAR_SYMBOL
         ::= CH_N CH_V CH_A CH_R CH_C CH_H CH_A CH_R 
OFFLINE_SYMBOL
         ::= CH_O CH_F CH_F CH_L CH_I CH_N CH_E 
OFFSET_SYMBOL
         ::= CH_O CH_F CH_F CH_S CH_E CH_T 
OLD_PASSWORD_SYMBOL
         ::= CH_O CH_L CH_D '_' CH_P CH_A CH_S CH_S CH_W CH_O CH_R CH_D 
ON_SYMBOL
         ::= CH_O CH_N 
ONE_SYMBOL
         ::= CH_O CH_N CH_E 
ONLINE_SYMBOL
         ::= CH_O CH_N CH_L CH_I CH_N CH_E 
ONLY_SYMBOL
         ::= CH_O CH_N CH_L CH_Y 
OPEN_SYMBOL
         ::= CH_O CH_P CH_E CH_N 
OPTIMIZE_SYMBOL
         ::= CH_O CH_P CH_T CH_I CH_M CH_I CH_Z CH_E 
OPTIMIZER_COSTS_SYMBOL
         ::= CH_O CH_P CH_T CH_I CH_M CH_I CH_Z CH_E CH_R '_' CH_C CH_O CH_S CH_T CH_S 
OPTIONS_SYMBOL
         ::= CH_O CH_P CH_T CH_I CH_O CH_N CH_S 
OPTION_SYMBOL
         ::= CH_O CH_P CH_T CH_I CH_O CH_N 
OPTIONALLY_SYMBOL
         ::= CH_O CH_P CH_T CH_I CH_O CH_N CH_A CH_L CH_L CH_Y 
ORDER_SYMBOL
         ::= CH_O CH_R CH_D CH_E CH_R 
OR_SYMBOL
         ::= CH_O CH_R 
OUTER_SYMBOL
         ::= CH_O CH_U CH_T CH_E CH_R 
OUTFILE_SYMBOL
         ::= CH_O CH_U CH_T CH_F CH_I CH_L CH_E 
OUT_SYMBOL
         ::= CH_O CH_U CH_T 
OWNER_SYMBOL
         ::= CH_O CH_W CH_N CH_E CH_R 
PACK_KEYS_SYMBOL
         ::= CH_P CH_A CH_C CH_K '_' CH_K CH_E CH_Y CH_S 
PAGE_SYMBOL
         ::= CH_P CH_A CH_G CH_E 
PARSER_SYMBOL
         ::= CH_P CH_A CH_R CH_S CH_E CH_R 
PARTIAL_SYMBOL
         ::= CH_P CH_A CH_R CH_T CH_I CH_A CH_L 
PARTITIONING_SYMBOL
         ::= CH_P CH_A CH_R CH_T CH_I CH_T CH_I CH_O CH_N CH_I CH_N CH_G 
PARTITIONS_SYMBOL
         ::= CH_P CH_A CH_R CH_T CH_I CH_T CH_I CH_O CH_N CH_S 
PARTITION_SYMBOL
         ::= CH_P CH_A CH_R CH_T CH_I CH_T CH_I CH_O CH_N 
PASSWORD_SYMBOL
         ::= CH_P CH_A CH_S CH_S CH_W CH_O CH_R CH_D 
PHASE_SYMBOL
         ::= CH_P CH_H CH_A CH_S CH_E 
PLUGINS_SYMBOL
         ::= CH_P CH_L CH_U CH_G CH_I CH_N CH_S 
PLUGIN_DIR_SYMBOL
         ::= CH_P CH_L CH_U CH_G CH_I CH_N '_' CH_D CH_I CH_R 
PLUGIN_SYMBOL
         ::= CH_P CH_L CH_U CH_G CH_I CH_N 
POINT_SYMBOL
         ::= CH_P CH_O CH_I CH_N CH_T 
POLYGON_SYMBOL
         ::= CH_P CH_O CH_L CH_Y CH_G CH_O CH_N 
PORT_SYMBOL
         ::= CH_P CH_O CH_R CH_T 
POSITION_SYMBOL
         ::= CH_P CH_O CH_S CH_I CH_T CH_I CH_O CH_N 
PRECEDES_SYMBOL
         ::= CH_P CH_R CH_E CH_C CH_E CH_D CH_E CH_S 
PRECISION_SYMBOL
         ::= CH_P CH_R CH_E CH_C CH_I CH_S CH_I CH_O CH_N 
PREPARE_SYMBOL
         ::= CH_P CH_R CH_E CH_P CH_A CH_R CH_E 
PRESERVE_SYMBOL
         ::= CH_P CH_R CH_E CH_S CH_E CH_R CH_V CH_E 
PREV_SYMBOL
         ::= CH_P CH_R CH_E CH_V 
PRIMARY_SYMBOL
         ::= CH_P CH_R CH_I CH_M CH_A CH_R CH_Y 
PRIVILEGES_SYMBOL
         ::= CH_P CH_R CH_I CH_V CH_I CH_L CH_E CH_G CH_E CH_S 
PROCEDURE_SYMBOL
         ::= CH_P CH_R CH_O CH_C CH_E CH_D CH_U CH_R CH_E 
PROCESS_SYMBOL
         ::= CH_P CH_R CH_O CH_C CH_E CH_S CH_S 
PROCESSLIST_SYMBOL
         ::= CH_P CH_R CH_O CH_C CH_E CH_S CH_S CH_L CH_I CH_S CH_T 
PROFILE_SYMBOL
         ::= CH_P CH_R CH_O CH_F CH_I CH_L CH_E 
PROFILES_SYMBOL
         ::= CH_P CH_R CH_O CH_F CH_I CH_L CH_E CH_S 
PROXY_SYMBOL
         ::= CH_P CH_R CH_O CH_X CH_Y 
PURGE_SYMBOL
         ::= CH_P CH_U CH_R CH_G CH_E 
QUARTER_SYMBOL
         ::= CH_Q CH_U CH_A CH_R CH_T CH_E CH_R 
QUERY_SYMBOL
         ::= CH_Q CH_U CH_E CH_R CH_Y 
QUICK_SYMBOL
         ::= CH_Q CH_U CH_I CH_C CH_K 
RANGE_SYMBOL
         ::= CH_R CH_A CH_N CH_G CH_E 
READS_SYMBOL
         ::= CH_R CH_E CH_A CH_D CH_S 
READ_ONLY_SYMBOL
         ::= CH_R CH_E CH_A CH_D '_' CH_O CH_N CH_L CH_Y 
READ_SYMBOL
         ::= CH_R CH_E CH_A CH_D 
READ_WRITE_SYMBOL
         ::= CH_R CH_E CH_A CH_D '_' CH_W CH_R CH_I CH_T CH_E 
REAL_SYMBOL
         ::= CH_R CH_E CH_A CH_L 
REBUILD_SYMBOL
         ::= CH_R CH_E CH_B CH_U CH_I CH_L CH_D 
RECOVER_SYMBOL
         ::= CH_R CH_E CH_C CH_O CH_V CH_E CH_R 
REDOFILE_SYMBOL
         ::= CH_R CH_E CH_D CH_O CH_F CH_I CH_L CH_E 
REDO_BUFFER_SIZE_SYMBOL
         ::= CH_R CH_E CH_D CH_O '_' CH_B CH_U CH_F CH_F CH_E CH_R '_' CH_S CH_I CH_Z CH_E 
REDUNDANT_SYMBOL
         ::= CH_R CH_E CH_D CH_U CH_N CH_D CH_A CH_N CH_T 
REFERENCES_SYMBOL
         ::= CH_R CH_E CH_F CH_E CH_R CH_E CH_N CH_C CH_E CH_S 
REGEXP_SYMBOL
         ::= CH_R CH_E CH_G CH_E CH_X CH_P 
RELAY_SYMBOL
         ::= CH_R CH_E CH_L CH_A CH_Y 
RELAYLOG_SYMBOL
         ::= CH_R CH_E CH_L CH_A CH_Y CH_L CH_O CH_G 
RELAY_LOG_FILE_SYMBOL
         ::= CH_R CH_E CH_L CH_A CH_Y '_' CH_L CH_O CH_G '_' CH_F CH_I CH_L CH_E 
RELAY_LOG_POS_SYMBOL
         ::= CH_R CH_E CH_L CH_A CH_Y '_' CH_L CH_O CH_G '_' CH_P CH_O CH_S 
RELAY_THREAD_SYMBOL
         ::= CH_R CH_E CH_L CH_A CH_Y '_' CH_T CH_H CH_R CH_E CH_A CH_D 
RELEASE_SYMBOL
         ::= CH_R CH_E CH_L CH_E CH_A CH_S CH_E 
RELOAD_SYMBOL
         ::= CH_R CH_E CH_L CH_O CH_A CH_D 
REMOVE_SYMBOL
         ::= CH_R CH_E CH_M CH_O CH_V CH_E 
RENAME_SYMBOL
         ::= CH_R CH_E CH_N CH_A CH_M CH_E 
REORGANIZE_SYMBOL
         ::= CH_R CH_E CH_O CH_R CH_G CH_A CH_N CH_I CH_Z CH_E 
REPAIR_SYMBOL
         ::= CH_R CH_E CH_P CH_A CH_I CH_R 
REPEATABLE_SYMBOL
         ::= CH_R CH_E CH_P CH_E CH_A CH_T CH_A CH_B CH_L CH_E 
REPEAT_SYMBOL
         ::= CH_R CH_E CH_P CH_E CH_A CH_T 
REPLACE_SYMBOL
         ::= CH_R CH_E CH_P CH_L CH_A CH_C CH_E 
REPLICATION_SYMBOL
         ::= CH_R CH_E CH_P CH_L CH_I CH_C CH_A CH_T CH_I CH_O CH_N 
REPLICATE_DO_DB_SYMBOL
         ::= CH_R CH_E CH_P CH_L CH_I CH_C CH_A CH_T CH_E '_' CH_D CH_O '_' CH_D CH_B 
REPLICATE_IGNORE_DB_SYMBOL
         ::= CH_R CH_E CH_P CH_L CH_I CH_C CH_A CH_T CH_E '_' CH_I CH_G CH_N CH_O CH_R CH_E '_' CH_D CH_B 
REPLICATE_DO_TABLE_SYMBOL
         ::= CH_R CH_E CH_P CH_L CH_I CH_C CH_A CH_T CH_E '_' CH_D CH_O '_' CH_T CH_A CH_B CH_L CH_E 
REPLICATE_IGNORE_TABLE_SYMBOL
         ::= CH_R CH_E CH_P CH_L CH_I CH_C CH_A CH_T CH_E '_' CH_I CH_G CH_N CH_O CH_R CH_E '_' CH_T CH_A CH_B CH_L CH_E 
REPLICATE_WILD_DO_TABLE_SYMBOL
         ::= CH_R CH_E CH_P CH_L CH_I CH_C CH_A CH_T CH_E '_' CH_W CH_I CH_L CH_D '_' CH_D CH_O '_' CH_T CH_A CH_B CH_L CH_E 
REPLICATE_WILD_IGNORE_TABLE_SYMBOL
         ::= CH_R CH_E CH_P CH_L CH_I CH_C CH_A CH_T CH_E '_' CH_W CH_I CH_L CH_D '_' CH_I CH_G CH_N CH_O CH_R CH_E '_' CH_T CH_A CH_B CH_L CH_E 
REPLICATE_REWRITE_DB_SYMBOL
         ::= CH_R CH_E CH_P CH_L CH_I CH_C CH_A CH_T CH_E '_' CH_R CH_E CH_W CH_R CH_I CH_T CH_E '_' CH_D CH_B 
REQUIRE_SYMBOL
         ::= CH_R CH_E CH_Q CH_U CH_I CH_R CH_E 
RESET_SYMBOL
         ::= CH_R CH_E CH_S CH_E CH_T 
RESIGNAL_SYMBOL
         ::= CH_R CH_E CH_S CH_I CH_G CH_N CH_A CH_L 
RESTORE_SYMBOL
         ::= CH_R CH_E CH_S CH_T CH_O CH_R CH_E 
RESTRICT_SYMBOL
         ::= CH_R CH_E CH_S CH_T CH_R CH_I CH_C CH_T 
RESUME_SYMBOL
         ::= CH_R CH_E CH_S CH_U CH_M CH_E 
RETURNED_SQLSTATE_SYMBOL
         ::= CH_R CH_E CH_T CH_U CH_R CH_N CH_E CH_D '_' CH_S CH_Q CH_L CH_S CH_T CH_A CH_T CH_E 
RETURNS_SYMBOL
         ::= CH_R CH_E CH_T CH_U CH_R CH_N CH_S 
RETURN_SYMBOL
         ::= CH_R CH_E CH_T CH_U CH_R CH_N 
REVERSE_SYMBOL
         ::= CH_R CH_E CH_V CH_E CH_R CH_S CH_E 
REVOKE_SYMBOL
         ::= CH_R CH_E CH_V CH_O CH_K CH_E 
RIGHT_SYMBOL
         ::= CH_R CH_I CH_G CH_H CH_T 
RLIKE_SYMBOL
         ::= CH_R CH_L CH_I CH_K CH_E 
ROLLBACK_SYMBOL
         ::= CH_R CH_O CH_L CH_L CH_B CH_A CH_C CH_K 
ROLLUP_SYMBOL
         ::= CH_R CH_O CH_L CH_L CH_U CH_P 
ROTATE_SYMBOL
         ::= CH_R CH_O CH_T CH_A CH_T CH_E 
ROUTINE_SYMBOL
         ::= CH_R CH_O CH_U CH_T CH_I CH_N CH_E 
ROWS_SYMBOL
         ::= CH_R CH_O CH_W CH_S 
ROW_COUNT_SYMBOL
         ::= CH_R CH_O CH_W '_' CH_C CH_O CH_U CH_N CH_T 
ROW_FORMAT_SYMBOL
         ::= CH_R CH_O CH_W '_' CH_F CH_O CH_R CH_M CH_A CH_T 
ROW_SYMBOL
         ::= CH_R CH_O CH_W 
RTREE_SYMBOL
         ::= CH_R CH_T CH_R CH_E CH_E 
SAVEPOINT_SYMBOL
         ::= CH_S CH_A CH_V CH_E CH_P CH_O CH_I CH_N CH_T 
SCHEDULE_SYMBOL
         ::= CH_S CH_C CH_H CH_E CH_D CH_U CH_L CH_E 
SCHEMA_SYMBOL
         ::= CH_S CH_C CH_H CH_E CH_M CH_A 
SCHEMA_NAME_SYMBOL
         ::= CH_S CH_C CH_H CH_E CH_M CH_A '_' CH_N CH_A CH_M CH_E 
SCHEMAS_SYMBOL
         ::= CH_S CH_C CH_H CH_E CH_M CH_A CH_S 
SECOND_MICROSECOND_SYMBOL
         ::= CH_S CH_E CH_C CH_O CH_N CH_D '_' CH_M CH_I CH_C CH_R CH_O CH_S CH_E CH_C CH_O CH_N CH_D 
SECOND_SYMBOL
         ::= CH_S CH_E CH_C CH_O CH_N CH_D 
SECURITY_SYMBOL
         ::= CH_S CH_E CH_C CH_U CH_R CH_I CH_T CH_Y 
SELECT_SYMBOL
         ::= CH_S CH_E CH_L CH_E CH_C CH_T 
SENSITIVE_SYMBOL
         ::= CH_S CH_E CH_N CH_S CH_I CH_T CH_I CH_V CH_E 
SEPARATOR_SYMBOL
         ::= CH_S CH_E CH_P CH_A CH_R CH_A CH_T CH_O CH_R 
SERIALIZABLE_SYMBOL
         ::= CH_S CH_E CH_R CH_I CH_A CH_L CH_I CH_Z CH_A CH_B CH_L CH_E 
SERIAL_SYMBOL
         ::= CH_S CH_E CH_R CH_I CH_A CH_L 
SESSION_SYMBOL
         ::= CH_S CH_E CH_S CH_S CH_I CH_O CH_N 
SERVER_SYMBOL
         ::= CH_S CH_E CH_R CH_V CH_E CH_R 
SERVER_OPTIONS_SYMBOL
         ::= CH_S CH_E CH_R CH_V CH_E CH_R '_' CH_O CH_P CH_T CH_I CH_O CH_N CH_S 
SESSION_USER_SYMBOL
         ::= CH_S CH_E CH_S CH_S CH_I CH_O CH_N '_' CH_U CH_S CH_E CH_R 
SET_SYMBOL
         ::= CH_S CH_E CH_T 
SET_VAR_SYMBOL
         ::= CH_S CH_E CH_T '_' CH_V CH_A CH_R 
SHARE_SYMBOL
         ::= CH_S CH_H CH_A CH_R CH_E 
SHOW_SYMBOL
         ::= CH_S CH_H CH_O CH_W 
SHUTDOWN_SYMBOL
         ::= CH_S CH_H CH_U CH_T CH_D CH_O CH_W CH_N 
SIGNAL_SYMBOL
         ::= CH_S CH_I CH_G CH_N CH_A CH_L 
SIGNED_SYMBOL
         ::= CH_S CH_I CH_G CH_N CH_E CH_D 
SIMPLE_SYMBOL
         ::= CH_S CH_I CH_M CH_P CH_L CH_E 
SLAVE_SYMBOL
         ::= CH_S CH_L CH_A CH_V CH_E 
SLOW_SYMBOL
         ::= CH_S CH_L CH_O CH_W 
SMALLINT_SYMBOL
         ::= CH_S CH_M CH_A CH_L CH_L CH_I CH_N CH_T 
SNAPSHOT_SYMBOL
         ::= CH_S CH_N CH_A CH_P CH_S CH_H CH_O CH_T 
SOME_SYMBOL
         ::= CH_S CH_O CH_M CH_E 
SOCKET_SYMBOL
         ::= CH_S CH_O CH_C CH_K CH_E CH_T 
SONAME_SYMBOL
         ::= CH_S CH_O CH_N CH_A CH_M CH_E 
SOUNDS_SYMBOL
         ::= CH_S CH_O CH_U CH_N CH_D CH_S 
SOURCE_SYMBOL
         ::= CH_S CH_O CH_U CH_R CH_C CH_E 
SPATIAL_SYMBOL
         ::= CH_S CH_P CH_A CH_T CH_I CH_A CH_L 
SPECIFIC_SYMBOL
         ::= CH_S CH_P CH_E CH_C CH_I CH_F CH_I CH_C 
SQLEXCEPTION_SYMBOL
         ::= CH_S CH_Q CH_L CH_E CH_X CH_C CH_E CH_P CH_T CH_I CH_O CH_N 
SQLSTATE_SYMBOL
         ::= CH_S CH_Q CH_L CH_S CH_T CH_A CH_T CH_E 
SQLWARNING_SYMBOL
         ::= CH_S CH_Q CH_L CH_W CH_A CH_R CH_N CH_I CH_N CH_G 
SQL_AFTER_GTIDS_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_A CH_F CH_T CH_E CH_R '_' CH_G CH_T CH_I CH_D CH_S 
SQL_AFTER_MTS_GAPS_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_A CH_F CH_T CH_E CH_R '_' CH_M CH_T CH_S '_' CH_G CH_A CH_P CH_S 
SQL_BEFORE_GTIDS_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_B CH_E CH_F CH_O CH_R CH_E '_' CH_G CH_T CH_I CH_D CH_S 
SQL_BIG_RESULT_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_B CH_I CH_G '_' CH_R CH_E CH_S CH_U CH_L CH_T 
SQL_BUFFER_RESULT_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_B CH_U CH_F CH_F CH_E CH_R '_' CH_R CH_E CH_S CH_U CH_L CH_T 
SQL_CACHE_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_C CH_A CH_C CH_H CH_E 
SQL_CALC_FOUND_ROWS_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_C CH_A CH_L CH_C '_' CH_F CH_O CH_U CH_N CH_D '_' CH_R CH_O CH_W CH_S 
SQL_NO_CACHE_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_N CH_O '_' CH_C CH_A CH_C CH_H CH_E 
SQL_SMALL_RESULT_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_S CH_M CH_A CH_L CH_L '_' CH_R CH_E CH_S CH_U CH_L CH_T 
SQL_SYMBOL
         ::= CH_S CH_Q CH_L 
SQL_THREAD_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_T CH_H CH_R CH_E CH_A CH_D 
SSL_SYMBOL
         ::= CH_S CH_S CH_L 
STACKED_SYMBOL
         ::= CH_S CH_T CH_A CH_C CH_K CH_E CH_D 
STARTING_SYMBOL
         ::= CH_S CH_T CH_A CH_R CH_T CH_I CH_N CH_G 
STARTS_SYMBOL
         ::= CH_S CH_T CH_A CH_R CH_T CH_S 
START_SYMBOL
         ::= CH_S CH_T CH_A CH_R CH_T 
STATS_AUTO_RECALC_SYMBOL
         ::= CH_S CH_T CH_A CH_T CH_S '_' CH_A CH_U CH_T CH_O '_' CH_R CH_E CH_C CH_A CH_L CH_C 
STATS_PERSISTENT_SYMBOL
         ::= CH_S CH_T CH_A CH_T CH_S '_' CH_P CH_E CH_R CH_S CH_I CH_S CH_T CH_E CH_N CH_T 
STATS_SAMPLE_PAGES_SYMBOL
         ::= CH_S CH_T CH_A CH_T CH_S '_' CH_S CH_A CH_M CH_P CH_L CH_E '_' CH_P CH_A CH_G CH_E CH_S 
STATUS_SYMBOL
         ::= CH_S CH_T CH_A CH_T CH_U CH_S 
STDDEV_SAMP_SYMBOL
         ::= CH_S CH_T CH_D CH_D CH_E CH_V '_' CH_S CH_A CH_M CH_P 
STDDEV_SYMBOL
         ::= CH_S CH_T CH_D CH_D CH_E CH_V 
STDDEV_POP_SYMBOL
         ::= CH_S CH_T CH_D CH_D CH_E CH_V '_' CH_P CH_O CH_P 
STD_SYMBOL
         ::= CH_S CH_T CH_D 
STOP_SYMBOL
         ::= CH_S CH_T CH_O CH_P 
STORAGE_SYMBOL
         ::= CH_S CH_T CH_O CH_R CH_A CH_G CH_E 
STORED_SYMBOL
         ::= CH_S CH_T CH_O CH_R CH_E CH_D 
STRAIGHT_JOIN_SYMBOL
         ::= CH_S CH_T CH_R CH_A CH_I CH_G CH_H CH_T '_' CH_J CH_O CH_I CH_N 
STRING_SYMBOL
         ::= CH_S CH_T CH_R CH_I CH_N CH_G 
SUBCLASS_ORIGIN_SYMBOL
         ::= CH_S CH_U CH_B CH_C CH_L CH_A CH_S CH_S '_' CH_O CH_R CH_I CH_G CH_I CH_N 
SUBDATE_SYMBOL
         ::= CH_S CH_U CH_B CH_D CH_A CH_T CH_E 
SUBJECT_SYMBOL
         ::= CH_S CH_U CH_B CH_J CH_E CH_C CH_T 
SUBPARTITIONS_SYMBOL
         ::= CH_S CH_U CH_B CH_P CH_A CH_R CH_T CH_I CH_T CH_I CH_O CH_N CH_S 
SUBPARTITION_SYMBOL
         ::= CH_S CH_U CH_B CH_P CH_A CH_R CH_T CH_I CH_T CH_I CH_O CH_N 
SUBSTR_SYMBOL
         ::= CH_S CH_U CH_B CH_S CH_T CH_R 
SUBSTRING_SYMBOL
         ::= CH_S CH_U CH_B CH_S CH_T CH_R CH_I CH_N CH_G 
SUM_SYMBOL
         ::= CH_S CH_U CH_M 
SUPER_SYMBOL
         ::= CH_S CH_U CH_P CH_E CH_R 
SUSPEND_SYMBOL
         ::= CH_S CH_U CH_S CH_P CH_E CH_N CH_D 
SWAPS_SYMBOL
         ::= CH_S CH_W CH_A CH_P CH_S 
SWITCHES_SYMBOL
         ::= CH_S CH_W CH_I CH_T CH_C CH_H CH_E CH_S 
SYSDATE_SYMBOL
         ::= CH_S CH_Y CH_S CH_D CH_A CH_T CH_E 
SYSTEM_USER_SYMBOL
         ::= CH_S CH_Y CH_S CH_T CH_E CH_M '_' CH_U CH_S CH_E CH_R 
TABLES_SYMBOL
         ::= CH_T CH_A CH_B CH_L CH_E CH_S 
TABLESPACE_SYMBOL
         ::= CH_T CH_A CH_B CH_L CH_E CH_S CH_P CH_A CH_C CH_E 
TABLE_REF_PRIORITY_SYMBOL
         ::= CH_T CH_A CH_B CH_L CH_E '_' CH_R CH_E CH_F '_' CH_P CH_R CH_I CH_O CH_R CH_I CH_T CH_Y 
TABLE_SYMBOL
         ::= CH_T CH_A CH_B CH_L CH_E 
TABLE_CHECKSUM_SYMBOL
         ::= CH_T CH_A CH_B CH_L CH_E '_' CH_C CH_H CH_E CH_C CH_K CH_S CH_U CH_M 
TABLE_NAME_SYMBOL
         ::= CH_T CH_A CH_B CH_L CH_E '_' CH_N CH_A CH_M CH_E 
TEMPORARY_SYMBOL
         ::= CH_T CH_E CH_M CH_P CH_O CH_R CH_A CH_R CH_Y 
TEMPTABLE_SYMBOL
         ::= CH_T CH_E CH_M CH_P CH_T CH_A CH_B CH_L CH_E 
TERMINATED_SYMBOL
         ::= CH_T CH_E CH_R CH_M CH_I CH_N CH_A CH_T CH_E CH_D 
TEXT_SYMBOL
         ::= CH_T CH_E CH_X CH_T 
THAN_SYMBOL
         ::= CH_T CH_H CH_A CH_N 
THEN_SYMBOL
         ::= CH_T CH_H CH_E CH_N 
TIMESTAMP_SYMBOL
         ::= CH_T CH_I CH_M CH_E CH_S CH_T CH_A CH_M CH_P 
TIMESTAMP_ADD_SYMBOL
         ::= CH_T CH_I CH_M CH_E CH_S CH_T CH_A CH_M CH_P '_' CH_A CH_D CH_D 
TIMESTAMP_DIFF_SYMBOL
         ::= CH_T CH_I CH_M CH_E CH_S CH_T CH_A CH_M CH_P '_' CH_D CH_I CH_F CH_F 
TIME_SYMBOL
         ::= CH_T CH_I CH_M CH_E 
TINYBLOB_SYMBOL
         ::= CH_T CH_I CH_N CH_Y CH_B CH_L CH_O CH_B 
TINYINT_SYMBOL
         ::= CH_T CH_I CH_N CH_Y CH_I CH_N CH_T 
TINYTEXT_SYMBOL
         ::= CH_T CH_I CH_N CH_Y CH_T CH_E CH_X CH_T 
TO_SYMBOL
         ::= CH_T CH_O 
TRAILING_SYMBOL
         ::= CH_T CH_R CH_A CH_I CH_L CH_I CH_N CH_G 
TRANSACTION_SYMBOL
         ::= CH_T CH_R CH_A CH_N CH_S CH_A CH_C CH_T CH_I CH_O CH_N 
TRIGGERS_SYMBOL
         ::= CH_T CH_R CH_I CH_G CH_G CH_E CH_R CH_S 
TRIGGER_SYMBOL
         ::= CH_T CH_R CH_I CH_G CH_G CH_E CH_R 
TRIM_SYMBOL
         ::= CH_T CH_R CH_I CH_M 
TRUE_SYMBOL
         ::= CH_T CH_R CH_U CH_E 
TRUNCATE_SYMBOL
         ::= CH_T CH_R CH_U CH_N CH_C CH_A CH_T CH_E 
TYPES_SYMBOL
         ::= CH_T CH_Y CH_P CH_E CH_S 
TYPE_SYMBOL
         ::= CH_T CH_Y CH_P CH_E 
UDF_RETURNS_SYMBOL
         ::= CH_U CH_D CH_F '_' CH_R CH_E CH_T CH_U CH_R CH_N CH_S 
UNCOMMITTED_SYMBOL
         ::= CH_U CH_N CH_C CH_O CH_M CH_M CH_I CH_T CH_T CH_E CH_D 
UNDEFINED_SYMBOL
         ::= CH_U CH_N CH_D CH_E CH_F CH_I CH_N CH_E CH_D 
UNDOFILE_SYMBOL
         ::= CH_U CH_N CH_D CH_O CH_F CH_I CH_L CH_E 
UNDO_BUFFER_SIZE_SYMBOL
         ::= CH_U CH_N CH_D CH_O '_' CH_B CH_U CH_F CH_F CH_E CH_R '_' CH_S CH_I CH_Z CH_E 
UNDO_SYMBOL
         ::= CH_U CH_N CH_D CH_O 
UNICODE_SYMBOL
         ::= CH_U CH_N CH_I CH_C CH_O CH_D CH_E 
UNINSTALL_SYMBOL
         ::= CH_U CH_N CH_I CH_N CH_S CH_T CH_A CH_L CH_L 
UNION_SYMBOL
         ::= CH_U CH_N CH_I CH_O CH_N 
UNIQUE_SYMBOL
         ::= CH_U CH_N CH_I CH_Q CH_U CH_E 
UNKNOWN_SYMBOL
         ::= CH_U CH_N CH_K CH_N CH_O CH_W CH_N 
UNLOCK_SYMBOL
         ::= CH_U CH_N CH_L CH_O CH_C CH_K 
UNSIGNED_SYMBOL
         ::= CH_U CH_N CH_S CH_I CH_G CH_N CH_E CH_D 
UNTIL_SYMBOL
         ::= CH_U CH_N CH_T CH_I CH_L 
UPDATE_SYMBOL
         ::= CH_U CH_P CH_D CH_A CH_T CH_E 
UPGRADE_SYMBOL
         ::= CH_U CH_P CH_G CH_R CH_A CH_D CH_E 
USAGE_SYMBOL
         ::= CH_U CH_S CH_A CH_G CH_E 
USER_RESOURCES_SYMBOL
         ::= CH_U CH_S CH_E CH_R '_' CH_R CH_E CH_S CH_O CH_U CH_R CH_C CH_E CH_S 
USER_SYMBOL
         ::= CH_U CH_S CH_E CH_R 
USE_FRM_SYMBOL
         ::= CH_U CH_S CH_E '_' CH_F CH_R CH_M 
USE_SYMBOL
         ::= CH_U CH_S CH_E 
USING_SYMBOL
         ::= CH_U CH_S CH_I CH_N CH_G 
UTC_DATE_SYMBOL
         ::= CH_U CH_T CH_C '_' CH_D CH_A CH_T CH_E 
UTC_TIMESTAMP_SYMBOL
         ::= CH_U CH_T CH_C '_' CH_T CH_I CH_M CH_E CH_S CH_T CH_A CH_M CH_P 
UTC_TIME_SYMBOL
         ::= CH_U CH_T CH_C '_' CH_T CH_I CH_M CH_E 
VALIDATION_SYMBOL
         ::= CH_V CH_A CH_L CH_I CH_D CH_A CH_T CH_I CH_O CH_N 
VALUES_SYMBOL
         ::= CH_V CH_A CH_L CH_U CH_E CH_S 
VALUE_SYMBOL
         ::= CH_V CH_A CH_L CH_U CH_E 
VARBINARY_SYMBOL
         ::= CH_V CH_A CH_R CH_B CH_I CH_N CH_A CH_R CH_Y 
VARCHAR_SYMBOL
         ::= CH_V CH_A CH_R CH_C CH_H CH_A CH_R 
VARCHARACTER_SYMBOL
         ::= CH_V CH_A CH_R CH_C CH_H CH_A CH_R CH_A CH_C CH_T CH_E CH_R 
VARIABLES_SYMBOL
         ::= CH_V CH_A CH_R CH_I CH_A CH_B CH_L CH_E CH_S 
VARIANCE_SYMBOL
         ::= CH_V CH_A CH_R CH_I CH_A CH_N CH_C CH_E 
VARYING_SYMBOL
         ::= CH_V CH_A CH_R CH_Y CH_I CH_N CH_G 
VAR_POP_SYMBOL
         ::= CH_V CH_A CH_R '_' CH_P CH_O CH_P 
VAR_SAMP_SYMBOL
         ::= CH_V CH_A CH_R '_' CH_S CH_A CH_M CH_P 
VIEW_SYMBOL
         ::= CH_V CH_I CH_E CH_W 
VIRTUAL_SYMBOL
         ::= CH_V CH_I CH_R CH_T CH_U CH_A CH_L 
WAIT_SYMBOL
         ::= CH_W CH_A CH_I CH_T 
WARNINGS_SYMBOL
         ::= CH_W CH_A CH_R CH_N CH_I CH_N CH_G CH_S 
WEEK_SYMBOL
         ::= CH_W CH_E CH_E CH_K 
WEIGHT_STRING_SYMBOL
         ::= CH_W CH_E CH_I CH_G CH_H CH_T '_' CH_S CH_T CH_R CH_I CH_N CH_G 
WHEN_SYMBOL
         ::= CH_W CH_H CH_E CH_N 
WHERE_SYMBOL
         ::= CH_W CH_H CH_E CH_R CH_E 
WHILE_SYMBOL
         ::= CH_W CH_H CH_I CH_L CH_E 
WITH_SYMBOL
         ::= CH_W CH_I CH_T CH_H 
WITHOUT_SYMBOL
         ::= CH_W CH_I CH_T CH_H CH_O CH_U CH_T 
WORK_SYMBOL
         ::= CH_W CH_O CH_R CH_K 
WRAPPER_SYMBOL
         ::= CH_W CH_R CH_A CH_P CH_P CH_E CH_R 
WRITE_SYMBOL
         ::= CH_W CH_R CH_I CH_T CH_E 
X509_SYMBOL
         ::= CH_X '509'
XA_SYMBOL
         ::= CH_X CH_A 
XID_SYMBOL
         ::= CH_X CH_I CH_D 
XML_SYMBOL
         ::= CH_X CH_M CH_L 
XOR_SYMBOL
         ::= CH_X CH_O CH_R 
YEAR_MONTH_SYMBOL
         ::= CH_Y CH_E CH_A CH_R '_' CH_M CH_O CH_N CH_T CH_H 
YEAR_SYMBOL
         ::= CH_Y CH_E CH_A CH_R 
ZEROFILL_SYMBOL
         ::= CH_Z CH_E CH_R CH_O CH_F CH_I CH_L CH_L 
PERSIST_SYMBOL
         ::= CH_P CH_E CH_R CH_S CH_I CH_S CH_T 
ROLE_SYMBOL
         ::= CH_R CH_O CH_L CH_E 
ADMIN_SYMBOL
         ::= CH_A CH_D CH_M CH_I CH_N 
INVISIBLE_SYMBOL
         ::= CH_I CH_N CH_V CH_I CH_S CH_I CH_B CH_L CH_E 
VISIBLE_SYMBOL
         ::= CH_V CH_I CH_S CH_I CH_B CH_L CH_E 
EXCEPT_SYMBOL
         ::= CH_E CH_X CH_C CH_E CH_P CH_T 
COMPONENT_SYMBOL
         ::= CH_C CH_O CH_M CH_P CH_O CH_N CH_E CH_N CH_T 
RECURSIVE_SYMBOL
         ::= CH_R CH_E CH_C CH_U CH_R CH_S CH_I CH_V CH_E 
JSON_OBJECTAGG_SYMBOL
         ::= CH_J CH_S CH_O CH_N '_' CH_O CH_B CH_J CH_E CH_C CH_T CH_A CH_G CH_G 
JSON_ARRAYAGG_SYMBOL
         ::= CH_J CH_S CH_O CH_N '_' CH_A CH_R CH_R CH_A CH_Y CH_A CH_G CH_G 
OF_SYMBOL
         ::= CH_O CH_F 
SKIP_SYMBOL
         ::= CH_S CH_K CH_I CH_P 
LOCKED_SYMBOL
         ::= CH_L CH_O CH_C CH_K CH_E CH_D 
NOWAIT_SYMBOL
         ::= CH_N CH_O CH_W CH_A CH_I CH_T 
GROUPING_SYMBOL
         ::= CH_G CH_R CH_O CH_U CH_P CH_I CH_N CH_G 
PERSIST_ONLY_SYMBOL
         ::= CH_P CH_E CH_R CH_S CH_I CH_S CH_T '_' CH_O CH_N CH_L CH_Y 
HISTOGRAM_SYMBOL
         ::= CH_H CH_I CH_S CH_T CH_O CH_G CH_R CH_A CH_M 
BUCKETS_SYMBOL
         ::= CH_B CH_U CH_C CH_K CH_E CH_T CH_S 
REMOTE_SYMBOL
         ::= CH_R CH_E CH_M CH_O CH_T CH_E 
CLONE_SYMBOL
         ::= CH_C CH_L CH_O CH_N CH_E 
CUME_DIST_SYMBOL
         ::= CH_C CH_U CH_M CH_E '_' CH_D CH_I CH_S CH_T 
DENSE_RANK_SYMBOL
         ::= CH_D CH_E CH_N CH_S CH_E '_' CH_R CH_A CH_N CH_K 
EXCLUDE_SYMBOL
         ::= CH_E CH_X CH_C CH_L CH_U CH_D CH_E 
FIRST_VALUE_SYMBOL
         ::= CH_F CH_I CH_R CH_S CH_T '_' CH_V CH_A CH_L CH_U CH_E 
FOLLOWING_SYMBOL
         ::= CH_F CH_O CH_L CH_L CH_O CH_W CH_I CH_N CH_G 
GROUPS_SYMBOL
         ::= CH_G CH_R CH_O CH_U CH_P CH_S 
LAG_SYMBOL
         ::= CH_L CH_A CH_G 
LAST_VALUE_SYMBOL
         ::= CH_L CH_A CH_S CH_T '_' CH_V CH_A CH_L CH_U CH_E 
LEAD_SYMBOL
         ::= CH_L CH_E CH_A CH_D 
NTH_VALUE_SYMBOL
         ::= CH_N CH_T CH_H '_' CH_V CH_A CH_L CH_U CH_E 
NTILE_SYMBOL
         ::= CH_N CH_T CH_I CH_L CH_E 
NULLS_SYMBOL
         ::= CH_N CH_U CH_L CH_L CH_S 
OTHERS_SYMBOL
         ::= CH_O CH_T CH_H CH_E CH_R CH_S 
OVER_SYMBOL
         ::= CH_O CH_V CH_E CH_R 
PERCENT_RANK_SYMBOL
         ::= CH_P CH_E CH_R CH_C CH_E CH_N CH_T '_' CH_R CH_A CH_N CH_K 
PRECEDING_SYMBOL
         ::= CH_P CH_R CH_E CH_C CH_E CH_D CH_I CH_N CH_G 
RANK_SYMBOL
         ::= CH_R CH_A CH_N CH_K 
RESPECT_SYMBOL
         ::= CH_R CH_E CH_S CH_P CH_E CH_C CH_T 
ROW_NUMBER_SYMBOL
         ::= CH_R CH_O CH_W '_' CH_N CH_U CH_M CH_B CH_E CH_R 
TIES_SYMBOL
         ::= CH_T CH_I CH_E CH_S 
UNBOUNDED_SYMBOL
         ::= CH_U CH_N CH_B CH_O CH_U CH_N CH_D CH_E CH_D 
WINDOW_SYMBOL
         ::= CH_W CH_I CH_N CH_D CH_O CH_W 
EMPTY_SYMBOL
         ::= CH_E CH_M CH_P CH_T CH_Y 
JSON_TABLE_SYMBOL
         ::= CH_J CH_S CH_O CH_N '_' CH_T CH_A CH_B CH_L CH_E 
NESTED_SYMBOL
         ::= CH_N CH_E CH_S CH_T CH_E CH_D 
ORDINALITY_SYMBOL
         ::= CH_O CH_R CH_D CH_I CH_N CH_A CH_L CH_I CH_T CH_Y 
PATH_SYMBOL
         ::= CH_P CH_A CH_T CH_H 
HISTORY_SYMBOL
         ::= CH_H CH_I CH_S CH_T CH_O CH_R CH_Y 
REUSE_SYMBOL
         ::= CH_R CH_E CH_U CH_S CH_E 
SRID_SYMBOL
         ::= CH_S CH_R CH_I CH_D 
THREAD_PRIORITY_SYMBOL
         ::= CH_T CH_H CH_R CH_E CH_A CH_D '_' CH_P CH_R CH_I CH_O CH_R CH_I CH_T CH_Y 
RESOURCE_SYMBOL
         ::= CH_R CH_E CH_S CH_O CH_U CH_R CH_C CH_E 
SYSTEM_SYMBOL
         ::= CH_S CH_Y CH_S CH_T CH_E CH_M 
VCPU_SYMBOL
         ::= CH_V CH_C CH_P CH_U 
MASTER_PUBLIC_KEY_PATH_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_P CH_U CH_B CH_L CH_I CH_C '_' CH_K CH_E CH_Y '_' CH_P CH_A CH_T CH_H 
GET_MASTER_PUBLIC_KEY_SYMBOL
         ::= CH_G CH_E CH_T '_' CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_P CH_U CH_B CH_L CH_I CH_C '_' CH_K CH_E CH_Y '_' CH_S CH_Y CH_M 
RESTART_SYMBOL
         ::= CH_R CH_E CH_S CH_T CH_A CH_R CH_T 
DEFINITION_SYMBOL
         ::= CH_D CH_E CH_F CH_I CH_N CH_I CH_T CH_I CH_O CH_N 
DESCRIPTION_SYMBOL
         ::= CH_D CH_E CH_S CH_C CH_R CH_I CH_P CH_T CH_I CH_O CH_N 
ORGANIZATION_SYMBOL
         ::= CH_O CH_R CH_G CH_A CH_N CH_I CH_Z CH_A CH_T CH_I CH_O CH_N 
REFERENCE_SYMBOL
         ::= CH_R CH_E CH_F CH_E CH_R CH_E CH_N CH_C CH_E 
OPTIONAL_SYMBOL
         ::= CH_O CH_P CH_T CH_I CH_O CH_N CH_A CH_L 
SECONDARY_SYMBOL
         ::= CH_S CH_E CH_C CH_O CH_N CH_D CH_A CH_R CH_Y 
SECONDARY_ENGINE_SYMBOL
         ::= CH_S CH_E CH_C CH_O CH_N CH_D CH_A CH_R CH_Y '_' CH_E CH_N CH_G CH_I CH_N CH_E 
SECONDARY_LOAD_SYMBOL
         ::= CH_S CH_E CH_C CH_O CH_N CH_D CH_A CH_R CH_Y '_' CH_L CH_O CH_A CH_D 
SECONDARY_UNLOAD_SYMBOL
         ::= CH_S CH_E CH_C CH_O CH_N CH_D CH_A CH_R CH_Y '_' CH_U CH_N CH_L CH_O CH_A CH_D 
ACTIVE_SYMBOL
         ::= CH_A CH_C CH_T CH_I CH_V CH_E 
INACTIVE_SYMBOL
         ::= CH_I CH_N CH_A CH_C CH_T CH_I CH_V CH_E 
LATERAL_SYMBOL
         ::= CH_L CH_A CH_T CH_E CH_R CH_A CH_L 
RETAIN_SYMBOL
         ::= CH_R CH_E CH_T CH_A CH_I CH_N 
OLD_SYMBOL
         ::= CH_O CH_L CH_D 
NETWORK_NAMESPACE_SYMBOL
         ::= CH_N CH_E CH_T CH_W CH_O CH_R CH_K '_' CH_N CH_A CH_M CH_E CH_S CH_P CH_A CH_C CH_E 
ENFORCED_SYMBOL
         ::= CH_E CH_N CH_F CH_O CH_R CH_C CH_E CH_D 
ARRAY_SYMBOL
         ::= CH_A CH_R CH_R CH_A CH_Y 
OJ_SYMBOL
         ::= CH_O CH_J 
MEMBER_SYMBOL
         ::= CH_M CH_E CH_M CH_B CH_E CH_R 
RANDOM_SYMBOL
         ::= CH_R CH_A CH_N CH_D CH_O CH_M 
MASTER_COMPRESSION_ALGORITHM_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_C CH_O CH_M CH_P CH_R CH_E CH_S CH_S CH_I CH_O CH_N '_' CH_A CH_L CH_G CH_O CH_R CH_I CH_T CH_H CH_M 
MASTER_ZSTD_COMPRESSION_LEVEL_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_Z CH_S CH_T CH_D '_' CH_C CH_O CH_M CH_P CH_R CH_E CH_S CH_S CH_I CH_O CH_N '_' CH_L CH_E CH_V CH_E CH_L 
PRIVILEGE_CHECKS_USER_SYMBOL
         ::= CH_P CH_R CH_I CH_V CH_I CH_L CH_E CH_G CH_E '_' CH_C CH_H CH_E CH_C CH_K CH_S '_' CH_U CH_S CH_E CH_R 
MASTER_TLS_CIPHERSUITES_SYMBOL
         ::= CH_M CH_A CH_S CH_T CH_E CH_R '_' CH_T CH_L CH_S '_' CH_C CH_I CH_P CH_H CH_E CH_R CH_S CH_U CH_I CH_T CH_E CH_S 
REQUIRE_ROW_FORMAT_SYMBOL
         ::= CH_R CH_E CH_Q CH_U CH_I CH_R CH_E '_' CH_R CH_O CH_W '_' CH_F CH_O CH_R CH_M CH_A CH_T 
PASSWORD_LOCK_TIME_SYMBOL
         ::= CH_P CH_A CH_S CH_S CH_W CH_O CH_R CH_D '_' CH_L CH_O CH_C CH_K '_' CH_T CH_I CH_M CH_E 
FAILED_LOGIN_ATTEMPTS_SYMBOL
         ::= CH_F CH_A CH_I CH_L CH_E CH_D '_' CH_L CH_O CH_G CH_I CH_N '_' CH_A CH_T CH_T CH_E CH_M CH_P CH_T CH_S 
REQUIRE_TABLE_PRIMARY_KEY_CHECK_SYMBOL
         ::= CH_R CH_E CH_Q CH_U CH_I CH_R CH_E '_' CH_T CH_A CH_B CH_L CH_E '_' CH_P CH_R CH_I CH_M CH_A CH_R CH_Y '_' CH_K CH_E CH_Y '_' CH_C CH_H CH_E CH_C CH_K 
STREAM_SYMBOL
         ::= CH_S CH_T CH_R CH_E CH_A CH_M 
OFF_SYMBOL
         ::= CH_O CH_F CH_F 
INT1_SYMBOL
         ::= CH_I CH_N CH_T '1'
INT2_SYMBOL
         ::= CH_I CH_N CH_T '2'
INT3_SYMBOL
         ::= CH_I CH_N CH_T '3'
INT4_SYMBOL
         ::= CH_I CH_N CH_T '4'
INT8_SYMBOL
         ::= CH_I CH_N CH_T '8'
SQL_TSI_SECOND_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_T CH_S CH_I '_' CH_S CH_E CH_C CH_O CH_N CH_D 
SQL_TSI_MINUTE_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_T CH_S CH_I '_' CH_M CH_I CH_N CH_U CH_T CH_E 
SQL_TSI_HOUR_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_T CH_S CH_I '_' CH_H CH_O CH_U CH_R 
SQL_TSI_DAY_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_T CH_S CH_I '_' CH_D CH_A CH_Y 
SQL_TSI_WEEK_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_T CH_S CH_I '_' CH_W CH_E CH_E CH_K 
SQL_TSI_MONTH_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_T CH_S CH_I '_' CH_M CH_O CH_N CH_T CH_H 
SQL_TSI_QUARTER_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_T CH_S CH_I '_' CH_Q CH_U CH_A CH_R CH_T CH_E CH_R 
SQL_TSI_YEAR_SYMBOL
         ::= CH_S CH_Q CH_L '_' CH_T CH_S CH_I '_' CH_Y CH_E CH_A CH_R 
WHITESPACE
         ::= [ #x9#xc#xd#xa]
INVALID_INPUT
         ::= [#x5B#x5D#x0001-#x0008#xB#xC#x000E-#x001F]
UNDERSCORE_CHARSET
         ::= UNDERLINE_SYMBOL [a-z0-9]+
IDENTIFIER
         ::= DIGITS+ ( [eE] ( LETTER_WHEN_UNQUOTED_NO_DIGIT LETTER_WHEN_UNQUOTED* )? | LETTER_WITHOUT_FLOAT_PART LETTER_WHEN_UNQUOTED* )
           | LETTER_WHEN_UNQUOTED_NO_DIGIT LETTER_WHEN_UNQUOTED*
NCHAR_TEXT
         ::= [nN] SINGLE_QUOTED_TEXT
BACK_TICK
         ::= '`'
SINGLE_QUOTE
         ::= "'"
DOUBLE_QUOTE
         ::= '"'
BACK_TICK_QUOTED_ID
         ::= BACK_TICK ( '\'? XML_CHAR )* BACK_TICK
DOUBLE_QUOTED_TEXT
         ::= ( DOUBLE_QUOTE ( ( '\' XML_CHAR ) | QUOTED_TEXT_CHAR | SINGLE_QUOTE )* DOUBLE_QUOTE )+
SINGLE_QUOTED_TEXT
         ::= ( SINGLE_QUOTE ( ( '\' XML_CHAR ) | QUOTED_TEXT_CHAR | DOUBLE_QUOTE )* SINGLE_QUOTE )+
POUND_COMMENT
         ::= '#' [^#xa#xd]*
DASHDASH_COMMENT
         ::= DOUBLE_DASH ( [ #x9] [^#xa#xd]* | LINEBREAK ) /* | EOF ) */
DOUBLE_DASH
         ::= '--'
LINEBREAK
         ::= [#xa#xd]
SIMPLE_IDENTIFIER
         ::= ( DIGIT | [a-zA-Z_$] | DOT_SYMBOL )+
LETTER_WHEN_UNQUOTED
         ::= DIGIT
           | LETTER_WHEN_UNQUOTED_NO_DIGIT
LETTER_WHEN_UNQUOTED_NO_DIGIT
         ::= [a-zA-Z_$#x0080-#xffff]
LETTER_WITHOUT_FLOAT_PART
         ::= [a-df-zA-DF-Z_$#x0080-#xffff]
/* EOF      ::= $ */

/* borrowed from W3C XML standard to replace the dot (Any Char) match
   which is not explicitly allowed in the EBNF notations */
XML_CHAR ::= [#x0001-#xD7FF#xE000-#xFFFD#x00010000-#x0010FFFF]
XML_CHAR_EXCEPT_QUOTES ::= [#x1-#x21#x23-#x26#x28-#xD7FF#xE000-#xFFFD#x00010000-#x0010FFFF]
ESCAPED_QUOTES ::= '\"' | "\'"
QUOTED_TEXT_CHAR ::= XML_CHAR_EXCEPT_QUOTES | ESCAPED_QUOTES
